### ISSUE TITLE
Courier will always follow bot if backpack is already full

### ISSUE THREAD

**Issue by mansarip** [adamqqqplay/dota2ai#1]
Hi, there are some cases when a bot want to receive an item from courier but the bot's backpack / slots is already full - the courier will always follow that bot anywhere.

For example, Omniknight already fill up his slots and backpack , but still wanted to receive items from courier, then this problem occurs.

**Comment by adamqqqplay** [comment]
Yeah, I have found this problem, and I added a condition in the courier function.
