### ISSUE TITLE
Bots do not use tokens to redeem neutral items. 

### ISSUE THREAD

**Issue by ArcherWayne** [adamqqqplay/dota2ai#112]
Bots do not use tokens to redeem neutral items. 

However, if the player redeemed a neutral item and sent it back, the neutral item will be picked up by a bot.

**Comment by adamqqqplay** [comment]
@ArcherWayne Dota2 does not provide corresponding neutral items API now, I think it is almost impossible to fix this issue.

Please track this issue at Dota2 side: https://github.com/ValveSoftware/Dota2-Gameplay/issues/8189 , giving an upvote emoji to this issue will make Valve's developer find it faster.

**Comment by ArcherWayne** [comment]
I think valve has updated the default bot since they can get neutral items prior to the "token" update. But redeeming any token is not within the default bot's capability currently. 

However, the API cannot be found in any official bot scripting documents, even though the Dota bot script wiki was recently updated on 1 June 2023.

**Comment by adamqqqplay** [comment]
@ArcherWayne We could keep this issue open so that more users will pay attention to this issue and feed it back to Valve.

**Comment by ArcherWayne** [comment]
Okay.
