### ISSUE TITLE
Heroes not buying items (RandomFloat is missing)

### ISSUE THREAD

**Issue by JoshdanG** [adamqqqplay/dota2ai#131]
It looks like the summer Dota update broke RandomFloat.  This is causing some major problems, the most obvious of which is that many bots are not buying items.

**Comment by JoshdanG** [comment]
Logged as an issue in the Dota 2 issues: https://github.com/ValveSoftware/Dota2-Gameplay/issues/11332

**Comment by adamqqqplay** [comment]
> It looks like the summer Dota update broke RandomFloat. This is causing some major problems, the most obvious of which is that many bots are not buying items.

This is really embarrassing, we don't have an effective channel to feedback AI-related issues to Valve.
