### ISSUE TITLE
Dota 2 bots script crash

### ISSUE THREAD

**Issue by CrossUCI** [adamqqqplay/dota2ai#15]
Hey guys , i download the proyect, i have the lastest client 7.14 , i copy into steamapps\common\dota 2 beta\game\dota\scripts\vscripts\ , i rename as bots, when i play with bots , client crash, someone can help me

**Comment by zmcmcc** [comment]
Don't rename vscripts as bots, but create a folder named bots and copy the codes in it.

**Comment by CrossUCI** [comment]
When i mean rename as bots was the project from github dota2ai-master, this folder i copy into vscripts and rename as bot , but as is said before the client crash

**Comment by zmcmcc** [comment]
try first create an empty folder "bots", and see if there's an option like "local test script" when you choose the bot script on your lobby.

**Comment by CrossUCI** [comment]
What happen , i live in Cuba so connecting to official steam server is an slow connecting and we have to pay, so here we use an steam emulator called TINserver, of course the client we updated directly from steam but not the server, the dota 2 game coordinator is on development so we can not create lobby yet we use console to create and join match in lan, but when you create the folder bots automatic you load the bots scripts

**Comment by zmcmcc** [comment]
Wow... Your case is special... It's beyond my knowledge...Maybe you can ask on Reddit for help? I'm not sure you can load the script without the server...Or search for if there's any way to play with bot script offline.

**Comment by zmcmcc** [comment]
@CrossUCI I made a test, closed the internet connection and log in on steam with offline mode. Then I started Dota2. I found I can not create a lobby, but I can start a bot game. And the bot is my script(I guess it is the script on the bots folder). So maybe you don't need to use the emulator, but rather try to get access to the internet for a second, log in with your account then you can turn off the internet and do as what I tried above.

**Comment by CrossUCI** [comment]
@zmcmcc The Steam emulator that i use allow you to create steam account and login, chat with other users, add friend all the funcionality of steam except the game coordinator, the game coordinator allow you to save statistic , manage lobby, achievements , but we dont have one  is on development,  etc, i made a test i copy the bots_example and rename as bots and it works , but i copy the hero_selection of your script and the client crash, i believe is something in this file. And as i said before i know it works because i have an old version of dota 7.10 and i played with  bots scripts, anywy thanks for all your answers.

**Comment by CrossUCI** [comment]
@zmcmcc I been ask in the forum of the Steam Emulator and someone answerme this 

> I  am using bots scripts in 7.13b, the ranked matchmaking IA which is the best there is. I have the 7.14 but I havent copied the script files into it, that file you refer to as master.zip is only the bots lua files or base script, but you will also need to have inside the game the other tools and folders (mods folder, and asset files inside dota) these are the one that tell the game to use the script instead of default and provide the resources to do so. Master.zip is not enough, it is the updateable part of a whole you have to install first. 

> 

So my questions is how i can get this mods folder and assets files.

**Comment by hannulak** [comment]
hi, i big fan. In the launch parameters of the Dota, the following commands are configured:
-steam -console –override_vpk +sv_cheats 1 +sv_lan 1 +dota_wait_for_players_to_load 100 +dota_wait_for_players_completed_delay 100 +dota_wait_for_players_to_load_timeout 100 +dota_bot_practice_start 1 +dota_start_ai_game 1 
Play with the bots until the 7.10, rencently the 7.13b update the client crash, now i try on 7.14, tell u later.
Other test command are:
sv_cheats 1
sv_lan 1
dota_bot_set_difficulty 4
dota_bot_reload_scripts
dota_start_ai_game 1
dota_force_gamemode 1
map dota.bsp
jointeam good/bad

i will test
Grettings
