### ISSUE TITLE
Broodmother poor performance

### ISSUE THREAD

**Issue by raphaell666** [adamqqqplay/dota2ai#19]
I had two games in a row with Broodmother bots that heavily under performed, finishing the game with sub 150 GPM and nearly no items and very few creep last hits. She seemed to not be using her spiderlings at all, they always seemed to be just standing around not doing anything. 

I saw that @zmcmcc has submitted a pull request with some updates, but I haven't tested it with this version yet.

**Comment by adamqqqplay** [comment]
Thanks for your advice! It is hard to program the Broodmother bot because it can cross the terrain. I have already seen this pull request and have merged it. From what I have already learned, this version does not modify the Broodmother. However, we will improve this hero in future versions.
