### ISSUE TITLE
一些问题...

### ISSUE THREAD

**Issue by suiyuan2009** [adamqqqplay/dota2ai#2]
1. 家都快被打爆，还tp到野区泉水
2. 一开始强行推中，强行守中，如果有一部分队友死了，还强行守，不断送人头
3. 推了外塔不满足，一个英雄或两个继续推二塔，送人头
4. 团战只有我在打，队友溜了...
5. 。。。

**Comment by adamqqqplay** [comment]
感谢反馈，在最新版本2和3应该修复了吧
