### ISSUE TITLE
关于 AI 抱团行为的一点疑惑

### ISSUE THREAD

**Issue by dnc1994** [adamqqqplay/dota2ai#20]
我用这个 AI 练习英雄很久了，有一个比较大的问题似乎一直存在：
在我带着 4 个 AI 打对面 5 个 AI 的前提下，到了中期对面就开始紧密抱团，而己方 AI 很少有这种意识。在对方 5 人平推一路时，己方 AI 有很大概率会在其他路游荡；即使选择防守，也很容易出现一个一个排队上去送的情况。
在没有巨大优势的前提下，1 v 5 是几乎不可能的。所以每次进入这种模式游戏就变得很难玩。是否因为我作为人类玩家没有跟着 AI 走，所以 AI 判断人数不齐不能抱团？

顺带提一下另外两个小问题：
1. 感觉 AI 对于守塔有点过于主动。大部分时候逼近一个非残血的塔对面就会 TP 好几个人下来。这使得 AI 很容易被带线流打崩。
2. AI 有时会发疯一般地追杀。在双方距离一直比较恒定的时候，AI 有时会做出类似于在 15 分钟的时候从一塔一直追杀到泉水的行为。

不过总体上这个 AI 还是很厉害，尤其是英雄技能的释放。有机会我也会试图参与开发 :)

**Comment by adamqqqplay** [comment]
你好，这些问题确实存在。但是大部分战略行为是由默认AI控制的，我的AI对此很难做修改，包括选择什么时候推塔，什么时候防守等等。如果未来有时间，那么便有可能对此做出改进，但仍然是很困难的。因为V社并没有放出原有AI的代码，修改则意味着完全重写，工作量比较大。
最后欢迎所有开发者对AI进行改进。
