### ISSUE TITLE
How to contribute? How to test developments? Roadmap?

### ISSUE THREAD

**Issue by simpsus** [adamqqqplay/dota2ai#22]
Dear owner,

I am a programmer and I would like to contribute towards improving this AI.
My question now is: How can I setup a development environment? I do not mean the IDE where I write code, but how do I test what I have just written? How can I debug and learn if the stuff that I did makes any sense?

Thank you very much.

**Comment by adamqqqplay** [comment]
Hi,

Sorry for the late reply. We are welcome everyone to contribute the project. The development environment is very simple, just need your Dota 2 Client. To test your code, you should copy the files into this folder "Steam\steamapps\common\dota 2 beta\game\dota\scripts\vscripts\bots", and then start the game chooes the local dev script. If you want to debug the code, you can open the console in game, and use "dota_bot_reload_script" to reload the code.
For more information, you can view the following page, 
https://developer.valvesoftware.com/wiki/Dota_Bot_Scripting
http://dev.dota2.com/forumdisplay.php?f=497
http://dota2.gamepedia.com/Cheats

Have a nice day!
