### ISSUE TITLE
[恶性bug]高台眼位改变导致AI原地打转

### ISSUE THREAD

**Issue by Diadormu** [adamqqqplay/dota2ai#48]
新版本高台眼位置改了之后，AI在中期会拿着眼在原来的高台下打转，不参团不守家。
还有啊，后期能不能也让AI出去插眼，我一个冰女要守家要1v5还要冒着生命危险自己出去插眼，我太难了:sob:

**Comment by adamqqqplay** [comment]
您好，我们在最新版本中已经尝试修复了这一bug，请您再次游玩并告诉我们最新的情况。
谢谢！

**Comment by Diadormu** [comment]
> 
> 
> 您好，我们在最新版本中已经尝试修复了这一bug，请您再次游玩并告诉我们最新的情况。
> 谢谢！

现在变成原地不动了
AI迷惑行为大赏：5995617694

**Comment by adamqqqplay** [comment]
> > 您好，我们在最新版本中已经尝试修复了这一bug，请您再次游玩并告诉我们最新的情况。
> > 谢谢！
> 
> 现在变成原地不动了
> AI迷惑行为大赏：5995617694

似乎是上次的更新没有同步到游戏客户端中，希望在这次的更新（v1.7.5）之后问题能够被解决

**Comment by Diadormu** [comment]
> 
> 
> > > 您好，我们在最新版本中已经尝试修复了这一bug，请您再次游玩并告诉我们最新的情况。
> > > 谢谢！
> > 
> > 
> > 现在变成原地不动了
> > AI迷惑行为大赏：5995617694
> 
> 似乎是上次的更新没有同步到游戏客户端中，希望在这次的更新（v1.7.5）之后问题能够被解决

还是那样,感觉上是ai想插眼，但是眼在背包里引起的。参考比赛：6004292488
猜测是ai不会把包里的东西拿出来，或者不会卖掉低级装备。

**Comment by AaronSong321** [comment]
@Diadormu This issue has been fixed in the latest version of this AI.
