### ISSUE TITLE
Hi quick suggest right here

### ISSUE THREAD

**Issue by 0MFCAT** [adamqqqplay/dota2ai#52]
Hello i just have a suggestion, can you make some way of the bots dont go allways the same ítem build? Its more fun if for example you make two builds for each Hero and they randomly pick one of them. Or at least create some way the comunity can create their own builds easily and make the bots use It.

Thanks for the attention and i like yo thanks too in the name of the Cuban dota gamers, we have very bad internet and very expensive so your bots help a lot. Thanks! :)

**Comment by AaronSong321** [comment]
We'll think about having different builds of items. The first item we're thinking about is to build a mekansm mechanism that one and only one player of a team builds mekansm as the first item (other than boots, etc.).
You can easily customise the behaviour of item build by cloning and modifying this repository if you have certain programming background of any language. For a hero called *hero*, the item purchase list can be found in file "item_purchase_*hero*.lua". You can modify the item list. Later items in the list can be built from previous items, so you can write:
```
"item_boots",
"item_arcane_boots",
```
to build arcane boots, where the hero buys boots first and then other components of arcane boots. Note that this project also needs the Mirana compiler, the website of which can also be found in the readme file.

**Comment by 0MFCAT** [comment]
Good i will try it, good work bros
