### ISSUE TITLE
I can help with testing

### ISSUE THREAD

**Issue by megastruktur** [adamqqqplay/dota2ai#97]
Hi guys!
Me and two my friends play with bots 100% of the time (3 or 2 vs 5 bots) for about 6 years. So we can help you testing your dev builds and report issues (I will report issues anyway though).
So if you're interested - please contact me at astromortis@gmail.com  😄

**Comment by adamqqqplay** [comment]
Thanks very much for your time, currently our development is mainly on github, so if there is an update, you can directly download the source code on github and install it locally.

If you find a problem, it is convenient to submit the issue directly, and its communication efficiency will be higher than email.
